# Generated by Django 5.2.7 on 2025-10-15 21:20

from django.db import migrations, models

def set_in_stock_true(apps, schema_editor):
    Product = apps.get_model('myapp', 'Product')
    Product.objects.update(in_stock=True)  # всем ставим True

def revert_in_stock(apps, schema_editor):
    Product = apps.get_model('myapp', 'Product')
    Product.objects.update(in_stock=False)  # откат — ставим False


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.RunPython(set_in_stock_true, revert_in_stock),
    ]
