# Generated by Django 5.2.7 on 2025-11-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
